### ISSUE TITLE
Precision of numbers in charts

### ISSUE THREAD

**Issue by cliffordh** [TelemetryDeck/Viewer#416] opened 2024-07-08 14:41 UTC
Reporting purchase using TelemetryDeck TelemetryDeck.Purchase.completed signal but seeing a precision error in the charts as shown.

```			
			TelemetryDeck.signal("TelemetryDeck.Purchase.completed",
										parameters: [
											"TelemetryDeck.Purchase.type": "subscription",
											"TelemetryDeck.Purchase.countryCode": country,
											"TelemetryDeck.Purchase.currencyCode": "USD"
										],
										floatValue: Double(0.99))
```

<img width="676" alt="Screenshot 2024-07-08 at 10 34 57 AM" src="https://github.com/TelemetryDeck/Issues/assets/1755156/33d7af56-9bdb-45be-8a29-ba454c207113">

**Comment by Jeehut** [comment] 2024-10-31 12:48
@cliffordh Hi, first of all, thank you for reporting this and sorry for getting back so late. I just investigated this issue to fix it, but I couldn't reproduce it. Can you maybe check if this is still a problem or if it was resolved by some change in the past 4 months? And if it still happens, can you provide some context? Thank you!

**Comment by Jeehut** [comment] 2024-11-26 18:16
@cliffordh One last ping before closing this issue. Does it still happen for you?

**Comment by Jeehut** [comment] 2024-12-01 10:05
Closing for now. Please let me know if you still run into this issue then I'll reopen.

**Closed as completed by Jeehut** 2024-12-01 10:05 UTC
Labels: bug
