### ISSUE TITLE
Duplicated insight name resets

### ISSUE THREAD

**Issue by Cykelero** [TelemetryDeck/Viewer#270] opened 2023-06-30 13:09 UTC
I'm having an issue while editing an insight.
Insight ID: EE69AAF8-28D5-4974-A89A-7AF8E9F08BC8

In some circumstances, changes to insight names are reverted.

1. Duplicate an insight. You're now of the duplicated insight's edit page.
2. Change this insight's name.
3. Modify the insight (e.g. change the filter criteria)
4. The name of the insight has been reverted (from the one you chose in step 2, to its original “XXX (copy)” value)

**Comment by jordibruin** [comment] 2023-07-07 23:39
Same here

**Comment by winsmith** [comment] 2023-07-10 13:38
Duplicate of #236 

Thanks for reporting, this is now the most reported bug ever! On it :D~

**Comment by jordibruin** [comment] 2023-08-05 17:33
It's still happening in case you deployed a fix

**Closed as completed** 2024-03-19 15:42 UTC
Labels: bug, Requested
