### ISSUE TITLE
Truncate leading a URL Values Breakdown

### ISSUE THREAD

**Issue by Timac** [TelemetryDeck/Viewer#264] opened 2023-06-19 18:13 UTC
- Add the Javascript SDK  to a website using anonymous users
- Create a Values Breakdown set to the URL

Result: All the URL in the compact view are leading truncated. I would rather like to have the urls leading truncated. That would be more useful. 

<img width="461" alt="URL" src="https://github.com/TelemetryDeck/Issues/assets/738543/9a2dc5b9-52ff-463f-b4d9-6ff29c62c5b8">

**Comment by winsmith** [comment] 2023-07-10 12:38
Dupe of #262

**Closed as not planned by winsmith** 2023-07-10 12:38 UTC
