### ISSUE TITLE
Insight Editor Issue

### ISSUE THREAD

**Issue by benrudhart** [TelemetryDeck/Viewer#441] opened 2024-08-21 06:38 UTC
I'm having an issue while editing an insiqht.

Insight ID: 08E30016-8ACC-4C15-8E22-16D4F43456EC

Please describe the issue:
I'm using the "Donut Chart" visualization type. If my data is coming in with a lot of different values, I'd like to be able to "group" them into "bucket". E.g. I'm looking at the count of something, then I don't want to see each single possible integer but grouped data, i.e. something like: 0-10, 10-20, 20-30, 30+.

Is it possible to setup my dashboards like this?

**Comment by winsmith** [comment] 2024-09-17 12:56
Not right now. What you need is Histogram functionality, which is on our roadmap for the future. I'm closing this ticket as a duplicate of https://github.com/TelemetryDeck/Issues/issues/406

**Closed as not planned by winsmith** 2024-09-17 12:56 UTC
