### ISSUE TITLE
Charts date multiple switches to NaN on mobile and then can't be edited

### ISSUE THREAD

**Issue by marcpalmer** [TelemetryDeck/Viewer#453] opened 2024-09-14 15:36 UTC
On Safari on iOS at least, if you try to change the date range and delete the default 6 for the number of months it switches to "NaN" and then refuses further edits. 

To work around this you have to enter the new quantity after the six e.g. set it to 61 then delete the 6. 

![image](https://github.com/user-attachments/assets/b3388461-ad6d-4596-aa57-18691d445dcf)

**Comment by Jeehut** [comment] 2024-09-17 16:30
@marcpalmer Thank you for reporting this. This issue should have been fixed in an update earlier today. I just tested in Mobile Safari (iOS 18.0.0) and couldn't reproduce, as expected. Please let me know if you still run into this issue!

Internal note: Fixed via https://github.com/TelemetryDeck/web/pull/1891.

**Closed as completed by Jeehut** 2024-09-17 16:30 UTC
Labels: bug
