### ISSUE TITLE
Improve custom time range UI in dashboard

### ISSUE THREAD

**Issue by KaiOelfke** [TelemetryDeck/Viewer#334] opened 2024-01-12 08:55 UTC
Say I want to compare a funnel insight for this month vs last month I may open two tabs and pick a different time range.

The UX for updating the time range is currently not good:

- the page will eventually reload potentially losing some pending edits in the time range UI
- I can't type in a number like 45 days and I often have to click 30 times to go from 30 days to one month
- It's not intuitive which arrow increases / decreases the number
- I can't do multiple edits as the page will reload according to bullet point one

**Comment by winsmith** [comment] 2024-01-22 09:01
Other customer: 

> I would like to simply specify a custom weekly date range like “Sep 4-10, 2023”. And then navigate the weeks back and forth. The custom range picker has some weird date controls that don’t let me do this.

**Comment by winsmith** [comment] 2024-06-26 13:28
Thanks! Closing this as a duplicate of https://github.com/TelemetryDeck/web/issues/1475

**Closed as completed by winsmith** 2024-06-26 13:28 UTC
Labels: papercut, Requested, Frontend
