### ISSUE TITLE
Human time range

### ISSUE THREAD

**Issue by magnusburton** [TelemetryDeck/Viewer#399] opened 2024-05-30 09:59 UTC
Hi! I'm in love with TelemtryDeck, thanks for this great service.
I do however have an issue with the time range component on the dashboard. I find it confusing and hard to work with. I'm like to suggest you to revamp the time range component into something similar to what Sentry uses. It has presets that you can choose from or a field where you wan enter '1m', '2h', '12h', '12 days' etc and it'll set the appropriate time range. See the attached picture.

![image](https://github.com/TelemetryDeck/Issues/assets/3188613/81068d4f-70c6-4f86-ab64-4338cf0baf53)

Best,
Magnus

**Comment by winsmith** [comment] 2024-06-26 13:28
Thanks! Closing this as a duplicate of https://github.com/TelemetryDeck/web/issues/1475

**Closed as completed by winsmith** 2024-06-26 13:28 UTC
